### ISSUE TITLE
Code to refactor

### ISSUE THREAD

**Issue by vizallati** [Nekembe-Boris/Inventory-manager#1]
https://github.com/Nekembe-Boris/Inventory-manager/blob/9cc7da79bf9ce0fe945b2dfe381ea5aa13644aa6/entry.py#L59

You're basically repeating the same lines of code over and over so you could refactor this by storing all the text params in a list and iterating over using a for loop

`options = ["Ceiling", "Equipments", "Electricity", "Masonry", "Plumbing", "Painting", "Scaffolding", "Tiling", "Waterproofing", "Others"]`
`for option in options:
   do something`
   
Same here: https://github.com/Nekembe-Boris/Inventory-manager/blob/9cc7da79bf9ce0fe945b2dfe381ea5aa13644aa6/auxillary_sec.py#L101
Same here as well: https://github.com/Nekembe-Boris/Inventory-manager/blob/9cc7da79bf9ce0fe945b2dfe381ea5aa13644aa6/language.py#L15

Wherever you are repeating the same code over and over but the only thing that changes is the params, it can be refactored which will make it easy to maintain and code will not be as lengthy

**Comment by vizallati** [comment]
You're basically repeating the same lines of code over and over so you could refactor this by storing all the  text in a list and iterating over using a for loop

**Comment by Nekembe-Boris** [comment]
Thank you for the review @vizallati . The code has been refactored as you prescribed.
